sot/mica

- mica/archive/aca_dark/update_aca_dark.py
```
File "/proj/sot/ska/arch/x86_64-linux_CentOS-6/lib/python2.7/site-packages/mica/archive/aca_dark/update_aca_dark.py", line 38, in <module>
MICA_FILES = pyyaks.context.ContextDict('update_mica_files', basedir='/tmp')
File "/proj/sot/ska/arch/x86_64-linux_CentOS-6/lib/python2.7/site-packages/pyyaks-3.3.3-py2.7.egg/pyyaks/context.py", line 251, in __new__
"({} vs. {})".format(name, basedir, CONTEXT[name].basedir))
ValueError: Re-using context name 'update_mica_files' but basedirs don't match (/tmp vs. /data/aca/archive)
```
> aca_dark update broken as of pyyaks 3.3.3

- mica/archive/obsid_archive.py
This code was attempting to get new asp1 products and rerun V&V
for all obsids that had "pending" or provisional data.  These changes
set it to fetch and check the version numbers of the content it has
and the "default" content and try to only fetch and redo V&V
(or mark to have V&V redone) if the state in the database has really
changed.
> Only rerun on new data

- mica/archive/aca_dark/dark_cal.py
```
Help on function get_dark_cal_props_table in module mica.archive.aca_dark.dark_cal:
get_dark_cal_props_table(start=None, stop=None, include_image=False, as_table=True)
Return a table of dark calibration properties between ``start`` and ``stop``.
If ``include_image`` is True then an additional column or key ``image`` is
defined which contains the corresponding 1024x1024 dark cal image.
```
```
----> 1 aca_dark.get_dark_cal_props_table(include_image=True)
/proj/sot/ska/arch/x86_64-linux_CentOS-5/lib/python2.7/site-packages/mica/archive/aca_dark/dark_cal.pyc in get_dark_cal_props_table(start, stop, include_image, as_table)
225         table_props = Table(props)
226         if include_image:
--> 227             x = np.vstack([prop['image'][np.newaxis, :] for prop in props])
228 …
```
> Fix include_image option in aca_dark.get_dark_cal_props_table

- mica/archive/aca_dark/dark_cal.py
- mica/archive/tests/test_aca_dark_cal.py
This changes the parametrization so that `scale_4c` is the multiplicative *increase* for each 4 degC *increase*.  Thus a bigger value is more increase.  That makes more sense and matches the way it was done for annealing.
This routine is back-compatible however.
> Add parameter to specify scaling factor in dark_temp_scale

- doc/index.rst
- mica/archive/obspar.py
- mica/archive/tests/test_obspar.py
There doesn't seem to be a convenient way to get all the obsids that have an available obspar file in the archive within a `start` / `stop` date range.
> Add function to get obspar obsids within a date range

- mica/vv/core.py
For warnings like:
"Warning: obsid 18842 has 2 aspect intervals"
it would be good to included "(has monitor window)" if, in fact, the observation does.  If it doesn't an email warn on this error would be useful.
> Improve multiple aspect interval warnings

- mica/version.py
- mica/web/pcad_table.py
Changes to get obsid 18625 to display in kadi acq table app
This also has the side-effect that the display will include the times through the start of KALM if present, and 5 minutes of data if there is no transition to KALM in the interval.
> Changes to get obsid 18625 to display in kadi acq table app

- doc/api.rst
- doc/index.rst
- mica/__init__.py
- mica/archive/aca_dark/dark_cal.py
- mica/archive/aca_l0.py
- mica/archive/tests/test_aca_dark_cal.py
- mica/archive/tests/test_aca_l0.py
- mica/archive/tests/validate_dark_coords.ipynb
- mica/version.py
- setup.py
Provide a complementary way to `get_slot_data()` of getting ACA L0 image data.
To do:
> Add get_l0_images function for ACA L0 using ACAImage class

- templates/vv_slots_single.html
When I am given a direct link like https://icxc.cfa.harvard.edu/aspect/mica_reports/16/16359/slot_4.html there is no easy way to get back to the main V&V report page.
> Nav links in report sub-pages

- mica/starcheck/process.py
- mica/starcheck/starcheck.sql
Replace shell "find" with os.walk in starcheck ingest
This code was set to try to find and ingest "new" starcheck.txt files using a Linux shell
"find" command set to find only files newer than the last ingested file. The time of the
last ingested file was stored by updating *another* file with that file's mod or change
time. The "find" command syntax was ugly, doing this in the shell was also not pretty, and
using a separate tracking file added a place where this could go wrong. This commit adds
the file mod time to the database (so an external tracking file isn't needed) and then
uses os.walk to get files and their mod times to include or exclude them from an update.
The os.walk code is borrowed from kadi.events.orbit_funcs .
The new P_ACQ column requires a database rebuild anyway, and …
> Replace shell "find" with os.walk

- templates/report.html
Remove extra empty lines between warnings in report
**Old:**
**New:**
> Remove extra empty lines between warnings in report

- mica/web/templates/mica/star_hist.html
- mica/web/views.py
Star history tweaks for #101 
Make some minor updates to the mica.web star history app.  These changes set the view to show the AGASC info for a star even if that star has no acquisition or guide history, change the size of a displayed header, and set the obsid string (for any previous acquisitions or use as a guide star) to be a link to the mica report web page.
> Star history tweaks

- mica/starcheck/starcheck.sql
- mica/starcheck/starcheck_parser.py
This PR is meant to accompany https://github.com/sot/starcheck/pull/190 to parse the new maneuver end times in starcheck.
```
OBSID: 53272  
RA, Dec, Roll (deg):   163.000000   -20.000000    89.145487
BACKSTOP GUIDE_SUMM OR MANVR DOT MAKE_STARS TLR 
MP_TARGQUAT at 2013:302:14:59:33.091 (VCDU count = 6607454)
Q1,Q2,Q3,Q4: -0.16732482  0.81354749  0.37632263  0.41051696
MANVR: Angle= 103.97 deg  Duration= 2046 sec  Slew err= 74.3
MANVR: Ends= 2013:302:15:33:34.000
MP_TARGQUAT at 2013:302:15:33:59.324 (VCDU count = 6615517)
Q1,Q2,Q3,Q4: -0.02018249  0.70184443  0.67581851  0.22422401
MANVR: Angle=  45.93 deg  Duration= 1274 sec  Slew err= 57.7
MANVR: Ends= 2013:302:15:55:08.000
MP_STARCAT at 2013:302:15:34:00.967 (VCDU count = 6615523)
```
Eventually, we should stop parsing starcheck.txt …
> Parse maneuver end date/time if in starcheck output

- mica/starcheck/process.py
- mica/starcheck/tests/make_database.py
Add a configurable start time for ingest of starcheck.txt files
#108 removed the need for the silly "touch file".  That was a file manually set with a timestamp and it was used in combination with an option to the shell "find" command to find files newer that that timestamp matching the pattern.  That was used to get "new" starcheck.txt files to update the database.  It was also how one could define a more recent time to, say, just get some recent files to  make a quick testing database.  This PR just adds a "start" time to the utility to have that option for testing.  Theoretically, I could also have just made a small /data/mpcrit1/ or used some similar technique to get just a handful of files for testing.
> Add a configurable start time for ingest of starcheck.txt files in the database

- mica/starcheck/process.py
Address minor issues in #110
Put in fixes suggested in review on #110 (updates for starcheck_parser to add a 'start' time for testing) that didn't get in due to speedy merging.  Fixes includes slightly simplifying the logic in on how a supplied 'start' time is handled and updating a comment. The larger issue noted in that review, specifically, the over-configuration problem, is temporarily offloaded to a new issue #111
> Address minor issues in #110

- mica/starcheck/starcheck_parser.py
Change regex to support manvr end time at end of line
Also update the setting of the number of segments (maneuver instances) at the end of the loop over the maneuvers instead of as they are found.
> Change regex for manvr end to end of line

- mica/stats/acq_stats.py
Handle a few missing obsids in acq stats
This fixes one bug introduced in https://github.com/sot/mica/commit/495c48a90fd48a53c8a29d3b36fa0357b70d045a .  Use of the new starcheck catalog fetcher can return None, which was not anticipated by the handling.  	2bbf4b9 helps to handle that case of no star catalog. 2e3db32 uses the most recent obspar to get times instead of the "default" obspar.  All use of the obspar should really be removed from this code in the future.
> Handle a few missing obsids in acq stats

- mica/starcheck/process.py
- mica/stats/acq_stats.py
- mica/version.py
Use chandra aca dark model (instead of mica version)
It looks like this was half-done (chandra_aca.dark_model added in imports but code to get_warm_fracs still using the mica.archive version).  This should go as another bugfix.
> Use chandra aca dark model (instead of mica version)

- mica/vv/core.py
- mica/vv/tests/test_vv.py
In V&V, handle case of uncommanded image window during Kalman.  The previous code assumed that any missing slots had entries in the ocat stars table.  This change checks to see if missing slots have entries in the table.  If a slot has no entry, it is just skipped.  This is designed for catalogs that are commanded with fewer than 8 used image windows during Kalman.
> In V&V, handle case of uncommanded image window during Kalman

- mica/vv/core.py
Use smaller markers on the YZ V&V plots to see the shape of the distribution. 
At some point a "heat map" style density plot for these could also make sense.
> Smaller markers on just the yz v&v plots

- mica/stats/acq_stats.py
- mica/stats/tests/test_acq_stats.py
Handle case of obsid with multiple dwells.  Obsids 15175 and 4911 have multiple dwells and were skipped in the previous version of this code.    Obsids have been added to test code.
> Handle case of obsid with multiple dwells

- mica/stats/guide_stats.py
- mica/stats/tests/test_guide_stats.py
Filter the tracked data used to calculate the star residual stats to only include samples in NPNT, KALM, and while tracking GUID stars.
> Filter tracked guide star data for reasonable stats

- mica/report/report.py
The update to fetch cmd_states from fetch_states instead of via the Sybase table introduced a tiny bug/IndexError.  
The update() code is not directly tested by module tests.
> Fix update() bug introduced by ec6f166

- mica/starcheck/starcheck.py
- mica/starcheck/starcheck_parser.py
- mica/starcheck/tests/test_catalog_fetches.py
Fix inconsistencies in queried starcheck database for observations without star catalogs.  The fixes include:
- ingesting maneuver information for observations with maneuver but without star catalog in starcheck output
- explicitly handling the case of an observation with a None/NULL entry for the star catalog time
> Fix inconsistencies in queried starcheck database for observations without star catalogs

- mica/archive/asp_l1.py
- mica/report/report.py
Minor fixes to remove/fix some displayed warnings
This cleans up an AstropyUserWarning and a DeprecationWarning when running the mica built-in tests.
> Minor fixes to remove/fix some displayed warnings

- mica/starcheck/starcheck.py
This let's get_starcheck_catalog_at_data succeed reasonably for a few dwells that have kadi manvrs that don't have nman_start defined and have more than one dwell for the maneuver.  The bits of code in this section were intended to help get the right catalog for the no-maneuver cases (multiple aspect intervals but same obsid), but it looks like a side effect was that some no-maneuver cases that *also* have segmented maneuvers don't work.  This is a small number of observations.
> Change use of manvr.nman_start to get star catalogs for a few obsids

- mica/stats/guide_stats.py
Only calculate guide stats over Kalman interval.  The first draft of the code fetched the data from then end of the previous maneuver, with the intent of looking both at guide and Kalman phases.  The current implementation is intended to just use the Kalman stars, but the interval between previous maneuver stop and Kalman start was still being included in some stats.  This was mostly an issue for ERs which have short overall intervals, so having an extra "penalty" of up to 30% of the time in not-track status (during the pre-Kalman period) was pulling a bunch of these stats down.
> Only calculate guide stats over Kalman interval

- doc/acq_stats.rst
- mica/stats/acq_stats.py
- mica/version.py
Use estimated-attitude-corrected box position to check for acquisition anomaly.  
The idea here is that the acq stats database already has these `dy` and `dz` elements which are calculated as the difference between the expected and actual position of the star, where the expected position is determined via the estimated attitude quaternion.  Therefore the `dy` `dz` of the tracked object is a little bit better at determining how far from the intended position the tracked object was than using "observed - catalog".  However, this isn't *quite* as good as using the actual commanded search box position, which would be the catalog position corrected for the estimated attitude *at the time of the search*.  The `dy` `dz` here in the database are at the time of the transition to guide.  
The …
> Use estimated-attitude-corrected box position to check for acquisition anomaly

- doc/guide_stats.rst
- mica/stats/guide_stats.py
These changes trim the first 60 seconds of each interval when calculating the position and magnitude-based stats.  The ends of intervals are also trimmed by a transition from NPNT, not the end of the Kalman interval (which I chose not to do because it would be harder to get full reacquisition sequences or other interesting states in the database) or the beginning of the next maneuver (what it was doing).
Stats such as the number of samples in SRCH do not have the first 60 seconds trimmed.
> Improve guide stats accuracy with more interval trimming

- mica/starcheck/starcheck_parser.py
- mica/version.py
Code that was intended to support not-breaking on intermediate maneuvers has a regex bug that is causing extra empty maneuvers to get in to the data structure.  This is breaking ingest.  This small bugfix doesn't fix the regex, but just stops the empty manvr entries from ending up in the data structure.
> Fix bug in parsing/ingest of manvrs

- mica/archive/cda_aca0_list.py
Update CDA script and improve debugging output.
Current failures in the cron job aren't reproducible at the cmd line and there isn't enough output from the cron job failures to see what is going on.  This PR should at least close the hdf5 file properly and might give enough debugging output to see  if there is a problem with the source data from the url.
> Update CDA script and improve debugging output

- mica/archive/asp_l1.py
Add hdu to asol and acal reads in get_atts_from_files
This is intended to fix warnings when run in ska3:
```
chandra_aca/tests/test_residuals.py::test_obc_centroids
/proj/sot/ska3/flight/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/astropy/io/fits/connect.py:110: AstropyUserWarning: hdu= was not specified but multiple tables are present, reading in first available table (hdu=1)
AstropyUserWarning)
```
(These tests are actually in chandra_aca, but this asol reading code is getting hit from there)
> Add hdu to asol and acal reads in get_atts_from_files

- mica/stats/guide_stats.py
npnt_tstop is a float and npnt_datestop is a string.  npnt_tstop was set with a string type and ingested that way, so the database will need a rebuild to be consistent.
> Fix npnt_tstop typo in guide stats database

- mica/archive/tests/test_aca_dark_cal.py
- mica/archive/tests/test_aca_hdr3.py
- mica/archive/tests/test_aca_l0.py
- mica/archive/tests/test_asp_l1.py
- mica/archive/tests/test_obspar.py
- mica/starcheck/tests/test_catalog_fetches.py
- mica/stats/tests/test_acq_stats.py
- mica/stats/tests/test_guide_stats.py
- mica/vv/tests/test_vv.py
A first pass at just skipping tests if components of the mica archive are not available to do those tests.
This is ugly due to overconfiguration of the paths.  Will clean that up in future PRs.
I haven't found a good way to skip all of the remaining tests in a file if a condition is met, so just copied the decorators down these files.
> Skip tests based on existence of parts of mica archive

- doc/guide_stats.rst
Update the guide stats table of column definitions to mark that RA and Dec are actually the proper-motion corrected values and not the 'RA' and 'DEC' values from the AGASC.
> Update RA/Dec definition (proper motion corrected) in docs

- mica/archive/aca_dark/dark_cal.py
This fixes a critical bug in `_get_dark_cal_image_props` where the `fits.open()` call uses the default `memmap=True` and thus leaves the file handle open despite the `hdus.close()` call.  It was discovered in proseco testing where running a few hundred obsids reached the Python limit for open files.
Can we get this and my previous 4 pull requests into a new release?  This is the only critical one, of course.
> Fix open file leak in reading  dark cals

- utilities/make_agasc_supplement.py
The idea is to install the new file `agasc_supplement.h5`  to `$SKA/data/agasc`.  
Later:
- Add some metadata with a key to the `source` column (maybe another table with the same `source` integer key and then a text string).
- Add new tables, e.g.:
- `observed` : observed mag / mag error, number of times as guide / acq, number of acq fails)
- `position` : position update
Then there will be a mica update script to keep it up to date on a daily basis.  For now this is useful and defines the basic structure and plan.
To do:
> Add utility script to create initial agasc_supplement.h5

- mica/archive/aca_dark/dark_cal.py
- mica/archive/tests/test_aca_dark_cal.py
Slightly controversial, but this makes the default in mica to clip negative values from dark maps returned by `dark_cal` functions.  
Since those values are not physical, I can't think of a good reason to not do this clipping globally by default.  Looking at SOT uses of [get_dark_cal_image](https://github.com/search?p=2&q=org%3Asot+get_dark_cal_image&type=Code) and [get_dark_cal_props](https://github.com/search?q=org%3Asot+get_dark_cal_props&type=Code) doesn't show anything that would break from not having negative pixel values (from what I saw).
There are doubtless non-versioned scripts or notebooks that show dark current distributions that would now be clipped and might require update.
> Clip negative dark map values by default

- mica/archive/aca_dark/dark_cal.py
- mica/archive/tests/test_aca_dark_cal.py
As noted at https://github.com/sot/acdc/pull/16#issuecomment-505983796, the acdc JSON properties file doesn't play with the current mica.  This should fix that.  In the mixed case, one gets back a masked table with the combined set of scalar attributes from the two different formats.
> Add support for acdc dark cal files

- mica/archive/aca_dark/dark_cal.py
- mica/archive/aca_dark/file_defs.py
I searched for SKA_FILES in sot org code and found no other matches.
This also removes an unnecessary `os.path.join`.
> Remove SKA_FILES context dict (unused after acdc transition)

- scripts/update_agasc_supplement.py
This provides a configured way to manually update the `agasc_supplement.h5` file to include a new bad star.  The prototype of 839258056 from obsid 22728 is the driver.
See also the companion wiki page: https://github.com/sot/mica/wiki/AGASC-supplement
This is well short of a nice automated system, but hopefully will suffice for now.
> Add update_agasc_supplement.py script

- mica/web/pcad_table.py
This import style (instead of "from kadi import events") is required due to a conflict with how the django app is initialized and standalone usage since django 2+. Basically `events/__init__.py` in a django app does not get the auto-generated query references because DJANGO_SETTINGS_MODULE is set.
This works in the ska3-django3 test environment using the django dev server:
> Fix an issue in PCAD table viewer with django 2+

- .git_archival.txt
- .gitattributes
- mica/__init__.py
- mica/web/pcad_table.py
- setup.py
This is based off the `scm_version` branch #211 (needed for testing), and includes a little fix in order to work with the kadi `py3-server` branch.
> Small fix for PCAD table generation + SCM version changes

- .gitignore
- doc/aca_dark_current.rst
- doc/api.rst
- mica/archive/aca_dark/__init__.py
- mica/archive/aca_dark/dark_model.py
Remove the `dark_model` module which has been deprecated for a while.  There are no instances of dark_model coming from mica in the `sot` org.
This is causing warnings now in pytest every time `mica.archive.aca_dark` gets imported.
Any code now importing dark modeling functions from `mica.archive.aca_dark` will now break.
> Remove dark model

- mica/archive/aca_dark/dark_cal.py
This implements the right upstream fix for https://github.com/sot/chandra_aca/issues/97.
```
In [1]: from mica.archive import aca_dark
In [2]: ccd_bgd = aca_dark.dark_cal.get_dark_cal_image('2019:001', aca_image=True)
In [3]: ccd_bgd.flicker_update(1)
In [4]:  # No failure
```
Fixes https://github.com/sot/chandra_aca/issues/97
> Recast dark cal image to native byte order

- mica/report/tests/test_write_report.py
Change sybase skip test to check for more restrictive vv creds
This should let the report-writing test that uses the axafvv query
run as jeanconn user, but skip for other users.
Fixes #
> Change sybase skip test to check for more restrictive vv creds

- mica/report/report.py
- mica/stats/acq_stats.py
- mica/stats/guide_stats.py
- mica/stats/update_acq_stats.py
Remove tables3_api imports.  Since we're no longer building tables3_api for shiny and it really isn't needed anymore (we're not doing Py2 backports) it is fine to just cut it here.
I think the unit testing is sufficient.
Fixes #
> Remove tables3_api imports

- mica/archive/aca_dark/dark_cal.py
- mica/archive/cda_aca0_list.py
- mica/archive/tests/test_aca_dark_cal.py
- mica/archive/tests/test_aca_hdr3.py
- mica/archive/tests/test_obspar.py
- mica/starcheck/starcheck.py
- mica/starcheck/tests/test_catalog_fetches.py
- mica/stats/update_acq_stats.py
- mica/stats/update_guide_stats.py
- pytest.ini
Updates for passing tests on shiny and remove import of `tables3_api`.
- [N/A] Functional testing
I have not confirmed passing tests on shiny / linux since that doesn't yet exist.
> Updates for passing tests on shiny

- mica/report/report.py
- mica/starcheck/process.py
- mica/starcheck/starcheck.py
This updates mica to use kadi.commands.states.get_states() instead of Chandra.cmd_states.
- [?] Functional testing
Not clear how to test the changes in `report.py`.
> Remove use of Chandra.cmd_states

- mica/report/report.py
- mica/report/tests/test_write_report.py
- mica/vv/core.py
Fix V&V handling of missing fid in shiny (also works in ska3-flight). 
Also set code to assume USER to run the axafvv queries so the V&V report making can work as user other than 'jeanconn'.
Set report writing test to work as USER as well and provide new warnings on Linux if the axafvv database access doesn't work.
Fixes #228, #179, #152
> More shiny fixes

- mica/archive/asp_l1.py
Make `get_atts` and friends work with modern ASPSOL data where the desired column is `q_att_raw` not `q_att`.
Via a temporary print statement, confirmed that `q_att_raw` is being used for obsid 23315 (recent) and `q_att` is being used for obsid 8008 (old).
> Use q_att_raw for ASPSOL quaternions if available

- mica/archive/asp_l1_proc.py
Don't throw error if there is more than one log (more than one aspect interval)
Fixes #243
> Don't throw error if there is more than one log (more than one aspect interval)

- docs/aca_dark_current.rst
Strictly speaking, this should be replaced by a new section with the right information. I just don't know what that is and want to get rid of the warnings.
Fixes #
> removed outdated documentation section

- .github/workflows/docs.yml
> added docs workflow

- mica/centroid_dashboard.py
- scripts/update_centroid_reports.py
- task_schedule.cfg
Toss the centroid dashboard code into mica
Fixes #
> Toss the centroid dashboard code into mica

- mica/archive/aca_l0.py
- mica/archive/tests/test_aca_l0.py
This PR adds the posibility to get the images with 8x8 shape from l0. This is used in the magnitude estimation algorithm.
> mod to be able to get 8x8 images in aca_l0.get_slot_data

- mica/archive/asp_l1.py
- mica/centroid_dashboard.py
- mica/starcheck/starcheck.py
A collection of fiddly little commits to: reduce extra processing, reduce skips or error-out observations, update page html to avoid reflows.
For functional testing, have just run a bunch of year 2020 with centroid dashboard code.  It is still filling in 
https://icxc.cfa.harvard.edu/aspect/centroid_reports
Fixes #
> More centroid_dashboard tweaks

- mica/vv/core.py
This is one fix for shiny (use a tuple instead of a list to remove a FutureWarning) and one fix due to an issue with monitor data in an obsid (22323) that looks to also be a problem in flight.
Fixes #
> Minor V&V fixes

- mica/archive/tests/test_asp_l1.py
Increase an ASOL quat vs OBC quat test tolerance by 4 arcsecs in roll.
The test_get_atts_time code currently runs through a bunch of machinery to compare ASOL quat with OBC quats and asserts they are within some tolerances.  It looks like the released ReproV version of an ASOL in this time range has a sample that is 1 arcsec worse in roll.  I've increased the tolerance from 51 to 55 in the test in this PR.  I could also, for example, set the code to used a fixed version of the ASOLs, but we've recently removed "old" released ASOL files from the archive and we may continue to trim, so I think maybe it makes sense for this code always get the last released ASOL for the comparison.
Fixes #
> Increase an ASOL quat vs OBC quat test tolerance by 4 arcsecs in roll

- mica/archive/aca_l0.py
- mica/archive/cda_aca0_list.py
Fix some L0 ingest hiccups.  
The ingest code was failing to ingest single new files in Repro.  It looks like that was due to a bug in identifying new files that had been downloaded.  I also hit a db locking issue that was improved by reorganizing.  And while at it, I updated the pieces needed to make a new archive (of the list of files released.. the "cda" h5 piece) to work more happily with shiny (removed six, updated some urllib pieces).  I was not rigorous distinguishing reproV from shiny updates here as I have just been working in shiny.
> L0 ingest issues (both shiny and repro V)

- mica/report/report.py
- mica/vv/core.py
- mica/vv/process.py
A few small V&V and mica.report updates.
This:
1. Updates the stored/saved version of the V&V entries made with the new code
2. Has a tiny fix to remove previous records in the V&V h5 table for a run if there were different numbers of slots saved (very unusual but should not stop processing)
3. Removes shelve support that was never really used
4. Adds a tiny fix to only add needed columns if "mocking up" a fidprop entry to do fid V&V on a fid that has been dropped from processing.
5. Is more rigorous opening and closing the V&V processing database as updates are done.
6. Updates version of report and fixes link to current centroid dashboard outputs
With regard to functional testing, given how these data are used and given that we store the version information, I moved to  running this …
> A few small V&V and report updates

- mica/archive/asp_l1.py
- mica/quaternion.py
- mica/stats/update_acq_stats.py
- mica/stats/update_guide_stats.py
- mica/vv/core.py
Use modern vectorized Quaternion.Quat instead of mica.quaterion
Did not do additional function testing except for spot-checking a few of the intermediate matrices to see if they looked reasonable compared to master.
Fixes #
> Use vectorized Quat

- scripts/update_centroid_reports.py
Fix script default to actually save plots.
The real answer is to cleanup all the defaults and rethink the options in centroid_dashboard, combined with actual entry-point scripts.  But this fixes the current script to at least make the plots.
- ran this live on the real archive and I see plots made.
Fixes #
> Fix script default to actually save plots

- mica/report/tests/test_write_report.py
- task_schedule.cfg
Skip report vv warn if no sybase passwd file for db
- ran as jeanconn and kadi user on Linux from production ska3 and see test pass and test skip as appropriate
Fixes #
> Skip report vv warn if no sybase passwd file for db

- mica/vv/process.py
Avoid vv obspar race condition.
With repro going on, we're getting a few V&V hiccups.  It looks like most are due to asp L1 products getting ingested in mica before obspars are available.  These PR changes 1) set the obspar ingest to run after the L1 ingest in the task schedule, 2) make the processing more robust to a missing obspar (log and skip).
I did not put time into creating a good functional test.  As this is a race condition situation, one would need to construct a state in the various databases matching the mismatch seen at the time of the V&V hiccup.  Given the benign nature of the changes, I think testing that this fixes the problem by just running the code in flight (and looking for warnings) makes sense.
Fixes #
> Avoid vv obspar race condition

- mica/archive/tests/test_asp_l1.py
- mica/stats/update_acq_stats.py
- mica/stats/update_guide_stats.py
- mica/vv/core.py
- mica/vv/tests/test_vv.py
Disable use of agasc supplement for stats and a specific vv use case
Also update a few vv tests newly failing due to repro.
> Disable use of agasc supplement for stats and a specific vv use case

- mica/stats/acq_stats.py
- mica/stats/guide_stats.py
- mica/stats/tests/test_acq_stats.py
- mica/stats/tests/test_guide_stats.py
- mica/web/star_hist.py
- mica/web/templates/mica/star_hist.html
- mica/web/views.py
Add some methods to do single star queries to the stats fetchers and update the mica.web star history piece to not use Sybase for guide stats.
Not fully integration tested in kadi just yet.
> Add get_star_stats single-star method for acq/gui stats and remove Sybase from mica.web.star_hist

- mica/stats/tests/test_acq_stats.py
- mica/stats/tests/test_guide_stats.py
Update the "skip if no obspars" test for test skipping to skip if the '00' directory isn't present within the obspars directory.  The obspars directory with one database file is now sync'd as part of ska_sync but the data for the tests in the subdirectories isn't there.
In this case the functional testing was the unit testing.
> Skip tests if obspar data dirs not present

- mica/web/star_hist.py
Fix not track percent so it is not track percent.
Silly bug.
For functional testing, I ran the kadi (python manage.py runserver) test server at master with this teeny mica fix in my PYTHONPATH and confirmed that we now see reasonable values in the "% not track" column for guide star history.
> Fix not track percent so it is not track percent

- mica/archive/cda_aca0_list.py
- task_schedule.cfg
Retry aca0 web query and ignore gateway errors in log checks
For functional testing I did a local edit (used a test URL that always returned an error) to test the retry.
> Retry aca0 web query and ignore gateway errors in log checks

- mica/report/report.py
Use CxoTime instead of DateTime and fix update() in mica.report.  As of kadi 5.9.1 get_states
called in update() cannot take "-7" as a relative time from now.
None
Independent check of unit tests by @taldcroft
I manually confirmed that the CxoTime calls give equivalent output to the DateTime calls.
> Use CxoTime and fix time range for update

- mica/report/report.py
- mica/starcheck/process.py
- mica/starcheck/tests/make_database.py
Remove uses of Ska.Shell that can be handled with builtin functions.
None
```
source /proj/sot/ska3/flight/bin/ska_envs.sh 
cd /proj/sot/ska/jgonzalez/git/mica
git fetch
git co ska-shell
export PYTHONPATH=`pwd`
cd test-pr-269/
```
and then in python:
```python
from mica.report import report
import getpass
import Ska.DBI
from pathlib import Path
user = getpass.getuser()
cwd = Path().absolute()
db = Ska.DBI.DBI(server='sqlsao', dbi='sybase', user=user, database='axafvv')  # as in test_write_reports
report.REPORT_ROOT = str(cwd)
report.REPORT_SERVER = str(cwd / 'test.db3')
for obsid in [20001, 15175, 54778]:
report.main(obsid)
```
and check that all image links are there as expected (dir contents are the same as with the latest release and links are …
> Remove use of Ska.Shell

- mica/archive/cda/services.py
- mica/archive/tests/test_cda.py
Improve the speed of reading the local OCAT. Most of the time is spent decoding the UTF-8
None.
Independent check of unit tests by Javier
```
(ska3) ➜  docs git:(ocat-local-faster) ipython
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from mica.archive.cda import get_ocat_local
In [2]: %time dat = get_ocat_local()
CPU times: user 1.69 s, sys: 83 ms, total: 1.77 s
Wall time: 1.77 s
```
```
(ska3) ➜  mica git:(ocat-local-faster) ipython
Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from mica.archive.cda import …
```
> Improve speed  of getting local OCAT data

- mica/archive/aca_dark/dark_cal.py
- mica/archive/tests/test_aca_dark_cal.py
This PR adds vectorized versions of get_dark_cal_id, date_to_dark_id and dark_id_to_date. It also replaces the uses of DateTime by CxoTime inside `mica.archive.aca_dark.dark_cal` (all other uses of `DateTime` were left there).
Everything *should* be backward compatible. This only enhances the interface, so something like this is possible:
```
get_dark_cal_id(['2022:100', '2022:105', '2022:127'], 'before')
```
I added a test for these vectorized functions.
Independent check of unit tests by @jeanconn 
> Added vectorized versions of some archive.dark_cal functions

- mica/archive/aca_dark/dark_cal.py
- mica/archive/tests/test_aca_dark_cal.py
This fixes a bug found in regression testing. `get_dark_cal_id` is vectorized using `np.vectorize`. When the input is a scalar, it returns a numpy scalar, but that is a numpy array with shape `()`. This has overloaded the bracket operators, so you can't call the bracket operators on the result. The solution is to return a scalar of the dtype's type.
None
mica unit tests and sparkles tests pass (including a new test for this)
> Fix issue in vectorized get_dark_cal_id

- mica/archive/aca_dark/dark_cal.py
- mica/archive/tests/test_aca_dark_cal.py
This PR adds an optional argument to `dark_cal.get_dark_cal_id`. Normally one calls this function like this:
```
dark_cal.get_dark_cal_id(time, 'before')
```
and internally it checks all dark-cal IDs to see which one is "closer" according to the given selection criterion. After this change, one will be able to do
```
dark_cal_ids = dark_cal.get_dark_cal_ids()
dark_cal.get_dark_cal_id(time, 'before', dark_cal_ids=dark_cal_ids)
```
The reason for this is that I am modifying aca_view to fetch data from the Ska API, and I would like to reduce the number of calls to the API. In the first call above, one gets the dark-cal ID for a given time, and the call might be repeated many times. This is unnecessary  because in most cases there will only be one dark-cal ID that applies to all times.
I …
> add optional dark_cal_ids argument to dark_cal.get_dark_cal_id

- mica/starcheck/__init__.py
- mica/starcheck/process.py
- mica/starcheck/starcheck.py
- mica/starcheck/tests/make_database.py
- mica/starcheck/tests/test_catalog_fetches.py
This tidies up the `mica.starcheck` subpackage in advance of removing the `timelines` database dependence.
None
The only non-automated check was fixing the regex expression in 26d18a4c108265998ead30b7a8827e86e73d90c0. (The forward slash `/` is not a special character and should not be escaped). I tested this with:
```
In [4]: st = '/data/mpcrit1/mplogs/2020/APR2020/oflsa/starcheck.txt'
In [5]:         mp_dir = re.search(
...:             r"/data/mpcrit1/mplogs(/\d{4}/\w{7}/\w{5}/)starcheck.txt", st
...:         ).group(1)
...: 
In [6]: mp_dir
Out[6]: '/2020/APR2020/oflsa/'
```
> starcheck subpackage: apply black and isort, fix line lengths, remove unused imports

- mica/vv/core.py
Fixes the FITS unit warning
Fixes #280
No FITS unit warning (but plenty of others).
> Fix FITS unit warning

- mica/report/report.py
This PR makes changes to avoid the following warning that currently appears in unit testing (`mica/report/tests/test_write_report.py::test_write_reports`):
```
TimeDeltaMissingUnitWarning: Numerical value without unit or explicit format passed to TimeDelta, assuming days
```
None
Ran mica unit tests without warning
> fix TimeDeltaMissingUnitWarning

- docs/api.rst
- mica/report/report.py
- mica/starcheck/process.py
- mica/starcheck/starcheck.py
- mica/starcheck/tests/test_catalog_fetches.py
- mica/stats/update_acq_stats.py
- mica/utils.py
- mica/web/pcad_table.py
- overview.rst
- pytest.ini
This removes the `cmd_states.db3` (and `timelines`) dependence from mica.
I'm not sure if any of these changes impact or break processing that is not covered in unit tests. This definitely needs close review by @jeanconn.
- It's possible that some old (pre-2003) queries may give different results.
- The `status` fields have been reduced/simplified and might give different results from the previous version.
None but many new unit tests.
> Remove timelines / cmd_states.db3 from mica

- mica/archive/cda/services.py
- mica/archive/tests/test_cda.py
Update CDA code and tests for DS10.12
It looks like 'ra' and 'dec' no longer work as aliases for 'lon' and 'lat' in the web services.  'jwst' looks to now be an output column.
'jwst' became a column in the ocat local data with DS10.12 but is not an interface impact of this PR.
Independent check of unit tests by Javier
> Update CDA code and tests for DS10.12

- mica/report/report.py
- mica/stats/update_acq_stats.py
- mica/stats/update_guide_stats.py
- mica/vv/core.py
- mica/web/views.py
Set mica agasc calls to use miniagasc*
This is in response to https://github.com/sot/agasc/pull/155 which changes the default agasc file to the most recent proseco agasc.  Overall that makes sense for operations, but bits of the mica code expect columns that aren't present in the proseco agasc.  It would probably be useful to update mica to just not use those columns (even for display) but for now I think it makes sense to update the calls in mica to use the miniagasc.  And this may end up being somewhat application specific in mica so I didn't set up any configuration for it.
mica tests don't pass with https://github.com/sot/agasc/pull/155 
Tested against a ska3-masters environment with https://github.com/sot/agasc/pull/155 .
No …
> Set mica agasc calls to use miniagasc*

- mica/report/report.py
- mica/report/tests/test_write_report.py
Tiny changes to handle no starcat observations better in reports.  For observations that do not have star catalogs (NMM dwells for IR zone especially) handle the missing star catalog with a handled exception instead of an error and don't try to parse the missing date.
Should stop the "Failed report on 44077" type errors.
Tested against a linux ska3-masters environment
Independent check of unit tests by Javier
Updated the report writing unit test to include a recent ER that has no star catalog.  With this PR that passes -- fails against master.
> Handle no-starcat observations better in reports

- mica/archive/tests/test_cda.py
Update test colnames for DS 10.12.3 outputs.
This is just renaming 'noao' to 'noirlab'.
Independent check of unit tests by @taldcroft
No functional changes or functional testing.
> Update test colnames for DS 10.12.3 outputs

- mica/stats/tests/test_acq_stats.py
- mica/stats/update_acq_stats.py
Skip any Exceptions in nominal processing over obsids.  The acq stats processing maneuver and dwell times don't make sense for obsid 62650 (causing IndexError) and it isn't worth the redesign of the code just now.  
This is the error in flight/master on the nsm / post-nsm obsid:
```
Skipping obsid 29211: No starcheck catalog found for 29211
Processing obsid 62620
Traceback (most recent call last):
File "/proj/sot/ska3/flight/lib/python3.10/site-packages/mica/stats/update_acq_stats.py", line 503, in calc_stats
raise ValueError
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/proj/sot/ska3/flight/share/mica/update_acq_stats.py", line 6, in <module> …
```
> Set acq stats processing to continue on individual obsid exceptions

- mica/stats/tests/test_acq_stats.py
- mica/stats/tests/test_guide_stats.py
In tests_acq/guide: close temp file before unlinking it.
From the docs:
> [mkstemp()](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp) returns a tuple containing an OS-level handle to an open file (as would be returned by [os.open()](https://docs.python.org/3/library/os.html#os.open))
Since the file is open, it should be close before unlinking. Otherwise, one gets this error on windows:
```
fh, fn = tempfile.mkstemp(suffix='.h5')
>       os.unlink(fn)
E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
```
I know we would not use this on windows most probably, but still...
After this PR, the test do not fail at this point in Windows. They fail later because …
> in tests_acq/guide: close temp file before unlinking it

- mica/centroid_dashboard.py
Remove np.str calls
Centroid dashboard fails with numpy error without this change.
```
(ska3-masters) jeanconn-fido> export SKA=/proj/sot/ska
(ska3-masters) jeanconn-fido> pytest
============================================================================ test session starts =============================================================================
platform linux -- Python 3.11.8, pytest-8.0.2, pluggy-1.4.0
plugins: timeout-2.2.0, anyio-4.3.0
collected 108 items                                                                                                                                                          
mica/archive/tests/test_aca_dark_cal.py .................. …
```
> Remove np.str calls

- mica/archive/obsid_archive.py
Update one remaining sybase call to use sqsh
```
ska3-jeanconn-fido> pytest
==================================================================== test session starts =====================================================================
plugins: anyio-4.3.0, timeout-2.2.0
collected 108 items                                                                                                                                          
mica/archive/tests/test_aca_dark_cal.py ..................                                                                                             [ 16%]
mica/archive/tests/test_aca_hdr3.py . …
```
> Update one remaining sybase call to use sqsh

- mica/archive/aca_l0.py
Handle filling aca image array differently
Fixes #293 
```
ska3-jeanconn-fido> git rev-parse HEAD
a1ca210964cbf815a3adce67bcd5323723b6f9c9
ska3-jeanconn-fido> pytest
================================================================= test session starts ==================================================================
plugins: anyio-4.3.0, timeout-2.2.0
collected 108 items                                                                                                                                    
mica/archive/tests/test_aca_dark_cal.py ..................                                                                                       [ 16%] …
```
> Handle filling aca image array differently

- mica/report/tests/test_write_report.py
Don't warn if kadi user can't access db in testing.
We could also just catch the warning in ska_testr, but I think maybe it is most useful here to not emit it.
Without this, you get
```
mica/report/tests/test_write_report.py:25
/proj/sot/ska/jeanproj/git/mica/mica/report/tests/test_write_report.py:25: UserWarning: On HEAD but Sqsh did not work. Unable to read inferred sqshrc file /proj/sot/ska/data/aspect_authorization/sqsh-sqlsao-axafvv-kadi
warn(f"On HEAD but Sqsh did not work. {e}")
```
```
ska3-jeanconn-kady> git rev-parse HEAD
061254c8e7696eb87b49f4388775a06ef9779a90
ska3-jeanconn-kady> pytest
============================================================================== test session starts ===============================================================================
platform linux …
```
> Don't warn if kadi user can't access db

- mica/stats/update_acq_stats.py
- mica/stats/update_guide_stats.py
Use full agasc for lookups for guide/acq stats.  With the healpix improvements, I don't think the speed difference matters for using the miniagasc.
I also don't see a driver to use different AGASC versions for *most* uses of the guide and acq stats of this time, given the small number of stars with very different positions - though we may want to review this in more detail if we do a full recalculation of the statistics. With the positions updates in AGASC 1.8 there would really be three positions, the observed centroids of the star, the expected position at the time the star catalog was constructed, and our best AGASC 1.8 estimate of the star position.
Fixes small issue in testing where a star in obsid 19386 is not in the 1p8 miniagasc and the ska_testr test log checking fails on the …
> Use full agasc for lookups for guide/acq stats

- mica/vv/core.py
Fix V&V processing error with Sqsh.  
Put the Sqsh calls in context managers instead of using an explicit conn.close that doesn't work on Sqsh.
Also change a couple of checks to use get() instead of checking "if self.info()["aspect_1_id"] is None" because for the nominal cases where there is a check on that value and the value doesn't exist, the key is also not defined and the error handling should be the same in that case.
Fixes issue that V&V processing was going through its paces but not getting the right information to update the status table.
```
(ska3-mica) jeanconn-fido> pytest
======================================================== test session starts ========================================================
rootdir: …
```
> Fix V&V processing error with Sqsh

- mica/stats/update_acq_stats.py
- mica/stats/update_guide_stats.py
Fix a processing error in acq and guide stats. This looks like a small bug introduced by #300 .  There's obviously more than one way to do the fix, but tbl.cols doesn't exist for a closed tbl.
I've been testing in a ska3-masters
```
jeanconn-fido> git rev-parse HEAD
ea27feae6766183826d0c3e5c9a5ef9601958e9e
========================================================= test session starts =========================================================
plugins: timeout-2.2.0, anyio-4.3.0
collected 108 items                                                                                                                   
mica/archive/tests/test_aca_dark_cal.py …
```
> Fix a processing error in acq and guide stats 

- mica/vv/core.py
Handle omitted star missing from miniagasc 1p8 in V&V.  
This code tweak is for a very specific case  - a star was used as a guide star in an historical observation, and *also* excluded from processing in the final aspect solution (either for centroid quality or position error or whatever).  For these OMITTED stars, the V&V code uses the agasc to make a "mock" entry for gsprops to calculate residuals and such for whatever data is available - if that star isn't in the miniagasc 1p8 the "mock" gsprops entry code was failing.   We could just handle the exception, but I figured it made just as much sense to use the full agasc for this processing code anyway.  I originally set this PR to use the 1.7 miniagasc, but I think that's a little too complicated and confusing.
It is a different …
> Handle omitted star missing from miniagasc 1p8 in V&V

- mica/centroid_dashboard.py
Add color1 to agasc fetch in centroid_dashboard.
This is required because of the changes in https://github.com/sot/chandra_aca/pull/170/files .
As COLOR1 is now used the the proseco acquisition mask, if calling code is using just a subset of columns, it needs that column too.  It is a different question about if the calling code should just be getting everything, but this fix to just include COLOR1 is trivial.
Fixes issue that the calls in centroid dashboard plotting will fail on the bad acquisition mask and end up with "KeyError: 'COLOR1' " if run in an environment with the modern chandra_aca and proseco with mask using COLOR1.
```
jeanconn-fido> git rev-parse HEAD
44a8278a372c263f5f1286fd3c561266455214c9
========================================================= …
```
> Add color1 to agasc fetch in centroid_dashboard

- mica/report/report.py
Fix "official V&V" truncated V&V html column
This fixes broken information in the "official" V&V table and will also keep the StringTruncateWarnings out of the log checking.  This was a missed side-effect of the transition to ska_dbi.Sqsh.  Since the value of "comments" can change later to a much longer string, and since this is generally a short list of records anyway, the V&V info can just be used as a dictionary instead of an astropy table.
In a relatively recent ska3-masters
```
=============================================================================================== test session starts ===============================================================================================
rootdir: …
```
> Fix truncated V&V html column

- mica/vv/core.py
Open up regex on file name and glob to work with Custom Process data.
This ends up coming up when Dale sends files for review for dark current checks etc, as the custom process files end up with axafm names or pcadm names or other variants.  I don't see a downside to just opening these expressions and globs up a bit.
```
jeanconn-fido> git rev-parse HEAD
55508a65cd334eba7dc8998d6b01a99e87319ad2
=============================================================================================== test session starts ===============================================================================================
plugins: timeout-2.2.0, anyio-4.3.0
collected …
```
> Open up regex on file name and glob to work with CP data

- mica/archive/tests/test_aca_l0.py
Exclude new IMG_VCDUCTR  from col comparison.  We could create this in mica in a new PR but it seems OK to just exclude and have tests pass for now.
This also removes the exception for END_INTEG_TIME, as with https://github.com/sot/chandra_aca/pull/180 that value should just match.
Lets tests pass if chandra_aca  has https://github.com/sot/chandra_aca/pull/180
```
ska3-flight-latest) LMABIUS-L1:mica jean$ cd ~/git/chandra_aca
(ska3-flight-latest) LMABIUS-L1:chandra_aca jean$ git rev-parse HEAD
00cc34738bebcd6b94f4e8bb999646bf9636351d
(ska3-flight-latest) LMABIUS-L1:chandra_aca jean$ cd ~/git/mica
(ska3-flight-latest) LMABIUS-L1:mica jean$ git rev-parse HEAD
40cc43aed699d4c69ecb08dc86426e70d2f60209
(ska3-flight-latest) LMABIUS-L1:mica jean$ pytest …
```
> Exclude new IMG_VCDUCTR image data from col comparison

- mica/archive/aca_l0.py
Unmask slot data columns as possible.
The intent is that this is the mica equivalent of 
https://github.com/sot/chandra_aca/pull/182
astropy Tables from mica.archive.aca_l0.get_aca_images will have masks only on columns with missing data (except for IMG).  IMGRAW is renamed IMG within the routine, so the actual unmasking excepts IMGRAW.
```
(ska3-flight-latest) flame:mica jean$ git rev-parse HEAD
5cf7011b866178f1f56e15dc12082ae4f16e96dd
(ska3-flight-latest) flame:mica jean$ pytest
===================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.11.8, pytest-8.0.2, pluggy-1.4.0
PyQt5 5.15.9 -- Qt runtime 5.15.8 -- Qt compiled 5.15.8 …
```
> Unmask aca image data columns (from get_aca_images) except for IMG

- mica/report/report.py
- mica/report/tests/test_report.py
- mica/stats/update_guide_stats.py
- mica/vv/core.py
Change report target_summary method to return unmasked dict or None
Fixes an issue that downstream code in the reporting was expecting either None or values None, not masked values.  This PR is a residual fix from the transition to using Sqsh for the database information.  It is a separate question if Sqsh.fetch_one should really return a dictionary with possible None values instead of an astropy table Row with masked values.
This changes the interface of mica.report.report.target_summary method, which looks to only be used internally.
```
jeanconn-fido> git rev-parse HEAD
b50a7bb8218db72b2d06151446065c932cebaf89
=============================================================== test session starts ================================================================ …
```
> Change report target_summary method to return dict or None

- mica/archive/tests/test_asp_l1.py
This is a change intended for skare3 > 2025.0, where we will use astropy 7.0. It replaces uses of `Table.pformat_all()` wih `Table.pformat()`. This silences a warning.
```
(ska3-flight-2025.0rc4) jgonzale mica $ pytest mica
============================================================= test session starts =============================================================
platform linux -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0
rootdir: /proj/sot/ska/jgonzalez/git
plugins: anyio-4.7.0, timeout-2.3.1
collected 112 items                                                                                                                           
mica/archive/tests/test_aca_dark_cal.py .................. …
```
> replace uses of pformat_all with pformat

- mica/report/tests/test_report.py
This PR makes changes to skip test_report.py::test_target_summary_or/er if sybase is not available.
Fixes issue that the target summary tests don't work on systems without Sybase/Sqsh access.
```
Switched to a new branch 'skip-test-report'
(2025.0) flame:mica jean$ pytest
============================================================================== test session starts ==============================================================================
platform darwin -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0
rootdir: /Users/jean/git
plugins: anyio-4.7.0, timeout-2.3.1
collected 112 items …
```
> skip test_report.py::test_target_summary_or/er

- mica/report/report.py
Set the matplotlib backend to Agg in mica.report.report.main()
This is meant to be run non-interactively.  It is generally called from scripts/update_reports.py which explicitly sets the backend to Agg, but if one needs to manually run reports, it would be a defect for it to not have the non-interactive backend set.  It also looks like for 2025.x that the test to write reports would fail trying to run with the interactive backend in a headless test env.
```
FAILED mica/report/tests/test_write_report.py::test_write_reports - ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
```
I could have fixed the test by just setting the backend for the test, but it seemed a bug in general for the code to try to use the …
> Set mica.report.report.main matplotlib backend to Agg

- mica/archive/aca_dark/dark_cal.py
- mica/archive/aca_hdr3.py
- mica/archive/cda/services.py
- mica/archive/tests/test_aca_hdr3.py
- mica/centroid_dashboard.py
- mica/report/report.py
- mica/stats/update_acq_stats.py
- mica/vv/process.py
- mica/web/views.py
- scripts/update_agasc_supplement.py
This fixes a bug in `two_byte_sum` where it is off by one for negative integers.
None
```
(ska3-flight-2025.0rc2) ➜  mica git:(fix-two-byte-sum) git rev-parse --short HEAD
0ade721
(ska3-flight-2025.0rc2) ➜  mica git:(fix-two-byte-sum) pytest                    
================================================================= test session starts =================================================================
platform darwin -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0
rootdir: /Volumes/git
plugins: doctestplus-1.3.0, anyio-4.7.0, timeout-2.3.1
collected 113 items                                                                                                                                   
mica/archive/tests/test_aca_dark_cal.py .................. …
```
> Use different alg for two_byte_sum that fixes off-by-one error

- mica/stats/update_acq_stats.py
- mica/stats/update_guide_stats.py
Limit stat update range to end of AOPCADMD data by default.
Fixes issue that more kadi.obsid events from https://github.com/sot/kadi/pull/343 could cause errors out of the update code.
```
ska3-jeanconn-fido> git rev-parse HEAD
69ec2ba4cf5262f233110b7a379bbd0c7a49776e
ska3-jeanconn-fido> pytest
============================= test session starts ==============================
platform linux -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0
plugins: anyio-4.7.0, timeout-2.3.1
collected 113 items                                                            
mica/archive/tests/test_aca_dark_cal.py ..................               [ 15%]
mica/archive/tests/test_aca_hdr3.py ..                                   [ 17%] …
```
> Limit stat update range to end of AOPCADMD data

- mica/stats/update_acq_stats.py
- mica/stats/update_guide_stats.py
Fix bug in acq/guide stats processing range
Also removes some old code that was intended to pause acquisition statistics if run during the hour that the kadi update process was supposed to run.  Now that code makes no sense as kadi update runs every ten minutes.
This PR fixes a bug I introduced in https://github.com/sot/mica/pull/318 where I assumed that when using an event filter that the keyword arg to stop__lte could be basically CxoTimeLike.   That's not true.  It looks like the filter will work if supplied a string or object, but doesn't work if given Chandra seconds.  
```
In [2]: obsids1 = events.obsids.filter(start="2025:104", stop__lte=CxoTime("2025:105").secs)
...: obsids1[len(obsids1) - 1]
Out[2]: <Obsid: start=2025:111:07:41:08.907 dur=5720 obsid=42463>
In [3]: obsids2 = …
```
> Fix bug in acq/guide stats processing range

- mica/archive/cda/services.py
- mica/archive/tests/test_cda.py
This PR fixes `archive.cds.get_proposal_abstract`. The current implementation of `archive.cds.get_proposal_abstract` fails if the abstract does not have any colon, and it truncates the abstract at **last** first colon it finds. The unit test was actually comparing to a truncated abstract, so the test itself was wrong.
This returns information with no abstract and gives the warning `failed to find Abstract in result`:
```
get_proposal_abstract(29944)
```
and this returns a truncated abstract:
```
In [38]: get_proposal_abstract(30454)
Out[38]: 
{'proposal_title': 'A hot shell bounding a young, multiphase, jet-driven outflow in a nearby galaxy',
'proposal_number': '26700420',
'principal_investigator': 'Grant Tremblay',
'abstract': 'We propose a 200 ksec HRC-I observation of a stunning …
```
> fix archive.cds.get_proposal_abstract

- mica/vv/core.py
- ruff-base.toml
- scripts/update_acq_stats.py
Update allowed size of acquisition database.
Because I used h5 badly when making the database, it grows I think via a leak mechanism.  So I've got the job set to ask me to repack it when it gets too big.  We could also auto-repack it or fix the underlying problem, but for now, I think it makes sense to increase the size where I get a warning, because the database when compressed is getting closer to the limit (it was 44Mb repacked today).
```
(ska3-latest) flame:mica jean$ pytest
====================================================================== test session starts =======================================================================
platform darwin -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0
rootdir: /Users/jean/git
plugins: socket-0.7.0, anyio-4.7.0, …
```
> Update allowed size of acquisition database
