sot/mica

mica/vv/core.py, mica/vv/process.py
Improve V&V logging by reducing verbosity, adding higher level notes (which obsid, which aspect interval), and adding a warning for multiple aspect intervals.
=> Improve V&V logging

mica/report/report.py
icxc2 is now deprecated for vv login.  This changes the path back to icxc.
=> Change path to icxc for vv login

setup.py
Also, `version` must be a string already.
=> Use setuptools not distutils

mica/starcheck/starcheck_parser.py
Set starcheck parser to ignore new P_ACQ column
=> Set starcheck parser to ignore new P_ACQ column

mica/report/report.py
Handle case of completely missing track mag in star report
=> Handle case of completely missing track mag in star report

mica/__init__.py, mica/vv/tests/test_vv.py, setup.py
Added some vv tests using the docs as a template
=> Add some vv tests using the docs as a template

mica/vv/core.py, mica/vv/tests/test_vv.py, mica/vv/vv.py
=> More mica.vv fixes for Py3

mica/__init__.py, mica/archive/aca_dark/__init__.py, mica/archive/aca_dark/dark_cal.py, mica/archive/aca_dark/dark_model.py, mica/archive/aca_dark/update_aca_dark.py, mica/archive/aca_hdr3.py, mica/archive/aca_l0.py, mica/archive/cda_aca0_list.py, mica/archive/obsid_archive.py, mica/archive/tests/test_aca_hdr3.py, mica/cache.py, mica/report/report.py, mica/starcheck/starcheck.py, mica/starcheck/starcheck_parser.py, mica/version.py, mica/vv/core.py, mica/vv/process.py, mica/vv/tests/test_vv.py, mica/vv/vv.py, setup.py
Passing tests except for test_aca_hdr3.py.
Got through most of the docs examples OK.  These should just be put into regression tests where sensible.
=> Python 3 compatibility

mica/vv/core.py
Change two remaining attribute refs (the rest went in py3 vv updates)
=> Change two remaining attribute refs (the rest went in py3 vv updates)

mica/web/star_hist.py, mica/web/templates/mica/star_hist.html, mica/web/views.py
Add star history kadi app
This is intended to replace
https://icxc.harvard.edu/cgi-bin/aspect/get_stats/get_stats.cgi?id=118494392
=> Add star history kadi app

mica/archive/aca_dark/dark_model.py, mica/version.py
Convert dark_model UserWarning to DeprecationWarning
=> Convert dark_model UserWarning to DeprecationWarning

mica/vv/core.py, mica/vv/tests/test_vv.py
Fix another py3 introduced bug and add tests
=> Bugfix: Fix another py3 introduced bug and add tests

doc/api.rst, doc/index.rst, mica/report/report.py, mica/starcheck/__init__.py, mica/starcheck/starcheck.py, mica/starcheck/tests/make_database.py, mica/starcheck/tests/test_catalog_fetches.py, mica/stats/acq_stats.py, mica/stats/tests/test_acq_stats.py, mica/utils.py, templates/report.html
Improve reliability of catalog fetches by obsid.  Add methods for catalog fetches by date and a convenience to get information about monitor windows.
=> Improve catalog queries and fetches

mica/vv/core.py, mica/vv/tests/test_vv.py
Bugfix: Fix omitted fid py3 introduced bug and add test
=> Bugfix: Fix omitted fid py3 introduced bug and add test

mica/stats/guide_stats.py
First draft of guide stats (based on acq stats)
=> First draft of guide stats 

Makefile, scripts/update_guide_stats.py, task_schedule.cfg
Add script and cron task for guide stats
Closes #123
=> Add script and cron task for guide stats

mica/archive/asp_l1.py, mica/archive/tests/test_asp_l1.py
Add a utility method to get quats from ranges of ground aspect solution files.
=> Add a utility method to get quats from asol ranges

mica/stats/acq_stats.py, mica/stats/guide_stats.py, mica/stats/tests/test_acq_stats.py, mica/stats/tests/test_guide_stats.py
Read guide and acq stats with Py3-compat tables_open_file.
=> Read and write guide and acq stats with tables3_api

mica/stats/acq_stats.py
The current email acquisition anomaly warnings are from the star_stats_db processing (which is the Python code that is updating the Sybase tables).  This PR adds an email warning for acquisition anomalies to mica acq_stats.  Unlike the current star_stat_db code, it actually checks to see if the data shows a "classic" acquisition anomaly or just a star with a large deviation from expected position.  Also unlike the star_stat_db code, it uses the halfwidth to check to see if the deviation is somewhat anomalous.
=> Add acquisition anomaly warnings

mica/archive/asp_l1.py
Separate method to get attitudes from asp1 files into new method.
=> Separate method to get attitudes from asp1 files into new method

mica/stats/guide_stats.py
Improve guide stats telem fetching and filtering per recommendation
=> Use more idiomatic fetch and filter syntax

doc/api.rst
Add get_atts and get_atts_from_files to api docs via sphinx autofunction
=> Add get_atts and get_atts_from_files to api docs

mica/catalog/__init__.py, mica/catalog/catalog.py
Use the chandra_aca version of the star field and catalog plotting codes and remove the mica duplicate.
=> Use chandra_aca.plot instead of mica.catalog.plot

mica/archive/archive.conf, mica/archive/asp_l1.py, mica/archive/obsid_archive.py, mica/archive/obspar.py, mica/common.py
Change the default location of the flight mica archive.
=> Move "flight" mica archive into /proj/sot/ska/data/mica/archive

mica/starcheck/__init__.py, mica/starcheck/starcheck.py, mica/starcheck/tests/test_catalog_fetches.py
Add convenience methods to mica.starcheck.
=> Add get_starcat, get_dither, and get_att methods to mica.starcheck

mica/archive/aca_l0.py, mica/archive/tests/test_aca_l0.py
Add IMGSCALE to default list for ACAImage meta.
=> Add IMGSCALE to default list for ACAImage meta

mica/starcheck/starcheck.py, mica/starcheck/tests/test_catalog_fetches.py
=> Fixes to starcheck for specifying mp_dir

mica/archive/aca_l0.py, mica/archive/obsid_archive.py, mica/archive/tests/test_aca_hdr3.py, mica/archive/tests/test_aca_l0.py, mica/report/report.py, mica/starcheck/tests/test_catalog_fetches.py
Fix module use of (removed) mica.version and fix up tests
=> Fix use of mica.version and tests

mica/report/report.py, mica/report/templates/report.html
Add link on report page to centroid dashboard page if available
=> Add link to centroid dashboard page if available

.git_archival.txt, .gitattributes, mica/__init__.py, setup.py
Implementation of setuptools_scm usage as described in sot/skare3/issues/240
=> Use setuptools_scm for single-source version

mica/report/report.py, mica/vv/vv.py, scripts/update_acq_stats.py, scripts/update_guide_stats.py
A bunch of tiny changes to get past processing bugs that didn't show up in the unit testing.
Fixes #
=> Silly process fixes

.github/workflows/release.yml
Use github token authentication instead of basic auth
=> Use github token authentication in workflow

mica/archive/asp_l1.py
I could never remember ACACENT, exactly.
- [N/A] Passes unit tests on MacOS, linux, Windows (at least one required)
- [N/A] Functional testing
=> Add list of available content types to asp_l1.get_files

mica/vv/tests/test_vv.py
Update spot check vv data test to use fixed version.
This is another case where ReproV changed/updated the reference data by a small amount.
=> Update spot check vv data test to use fixed version

mica/bad_obsids.py
Add two new obsids to bad list
Fixes #
=> Add two new obsids to bad list

mica/archive/aca_l0.py, mica/archive/asp_l1_proc.py, mica/archive/obsid_archive.py, mica/archive/tests/test_asp_l1.py, mica/report/report.py, mica/report/tests/test_write_report.py, mica/starcheck/process.py, mica/starcheck/starcheck.py, mica/vv/core.py, mica/vv/process.py, mica/vv/vv.py, utilities/set_arch_defaults.py
Update to use ska_dbi sqsh in https://github.com/sot/ska_dbi/pull/25
Requires https://github.com/sot/ska_dbi/pull/25 .
```
ska3-jeanconn-fido> git rev-parse HEAD
748204c450f7461b29c299f52a4e294ff043302b
ska3-jeanconn-fido> pytest
====================================================================== test session starts =======================================================================
platform linux -- Python 3.10.8, pytest-7.2.1, pluggy-1.0.0
rootdir: /proj/sot/ska/jeanproj/git, configfile: pytest.ini
plugins: anyio-3.6.2, timeout-2.1.0
collected 108 items                                                                                                                                              
mica/archive/tests/test_aca_dark_cal.py .................. …
```
=> Update mica to use ska_dbi sqsh
